# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o newsletter-web ./cmd/web

# Final image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/newsletter-web .
COPY --from=builder /app/env ./env

CMD ["./newsletter-web"]
