# Build stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o newsletter-worker ./cmd/worker

# Final image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/newsletter-worker .
COPY --from=builder /app/env ./env

CMD ["./newsletter-worker"]
